apiVersion: v1
kind: Service
metadata:
  name: {{ include "token-stack.goName" . }}
  labels:
    {{- include "token-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: go
spec:
  type: ClusterIP
  selector:
    {{- include "token-stack.selectorLabels" (dict "root" . "component" "go") | nindent 4 }}
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
