apiVersion: v1
kind: Service
metadata:
  name: {{ include "token-stack.pythonName" . }}
  labels:
    {{- include "token-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: python
spec:
  type: ClusterIP
  selector:
    {{- include "token-stack.selectorLabels" (dict "root" . "component" "python") | nindent 4 }}
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
