# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: token.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'token.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btoken.proto\x12\x05token\"P\n\x10MintTokenRequest\x12\x12\n\nuser_email\x18\x01 \x01(\t\x12\x13\n\x0bpermissions\x18\x02 \x03(\t\x12\x13\n\x0bttl_seconds\x18\x03 \x01(\x05\"\"\n\x11MintTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\":\n\x15ValidateTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x12\n\nuser_email\x18\x02 \x01(\t2\x9a\x01\n\x0cTokenService\x12>\n\tMintToken\x12\x17.token.MintTokenRequest\x1a\x18.token.MintTokenResponse\x12J\n\rValidateToken\x12\x1b.token.ValidateTokenRequest\x1a\x1c.token.ValidateTokenResponseB\x15Z\x13token-service/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'token_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023token-service/proto'
  _globals['_MINTTOKENREQUEST']._serialized_start=22
  _globals['_MINTTOKENREQUEST']._serialized_end=102
  _globals['_MINTTOKENRESPONSE']._serialized_start=104
  _globals['_MINTTOKENRESPONSE']._serialized_end=138
  _globals['_VALIDATETOKENREQUEST']._serialized_start=140
  _globals['_VALIDATETOKENREQUEST']._serialized_end=177
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=179
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=237
  _globals['_TOKENSERVICE']._serialized_start=240
  _globals['_TOKENSERVICE']._serialized_end=394
# @@protoc_insertion_point(module_scope)
